services:
  - type: web
    name: pdf-merger
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn pdf_merger:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9 